### ISSUE TITLE
Specific filename format required?

### ISSUE THREAD

**Issue by mlevison** [brandonkboswell/reflection#3]
I can't tell from the docs (or code) if this relies on a specific filename format? Looking at the https://github.com/liamcain/obsidian-daily-notes-interface - I can't see anything except a mention of a dateUID. (I've not noticed this embedded in any Obsidian file I've ever created.

**Comment by brandonkboswell** [comment]
Hey Mark, this uses the [Periodic Notes Plugin](https://github.com/liamcain/obsidian-periodic-notes). AFAIK the Periodic Notes plugin uses specific folders, to determine the type of each note.

**Comment by mlevison** [comment]
Brandon for the quick response. I guess the question becomes how does Period Notes tell? I ask because I've tried a few file formats over time. Many are in YYYY-MM-DD and now I used YYYY-MM-DD-ddd because I like to see the weekday associated with a note. I'm trying to figure out if I have batch of code to write to convert filenames to a the current format.

**Comment by brandonkboswell** [comment]
You can configure this in the Periodic Notes Plugin settings. 
![BKB 2023-10-11 at 12 35 47](https://github.com/brandonkboswell/reflection/assets/921925/f8a64ebc-beb7-4f1b-ab4f-1ec3270d6373)

**Comment by kennonb** [comment]
So I'm not seeing anything posted in my files as well. I definitely have files created in all of October 2023 and 2022, so theoretically I should see those notes in my dailies. I have customized the Periodic Notes plugin quite a bit though, so I'm wondering if maybe I've done something that's broken it somehow? 

I don't see any console errors though, so my guess is that it's working correctly. 🤷🏻‍♂️ I'm going to post a few screenshots, but if you know of anything else I could send that might shed some light here just let me know.

![CleanShot 2023-10-29 at 19 50 02@2x](https://github.com/brandonkboswell/reflection/assets/76159/9605a2f3-869b-43bf-b86a-b845861db31b)

![CleanShot 2023-10-29 at 19 51 22@2x](https://github.com/brandonkboswell/reflection/assets/76159/d8a7f5bf-4910-4e84-9503-2f1213db519d)

![CleanShot 2023-10-29 at 19 51 46@2x](https://github.com/brandonkboswell/reflection/assets/76159/4fce34f0-5200-4d0c-bb14-63da00103d8d)

**Comment by mlevison** [comment]
@kennonb This might now help you, but my massive realization for me. Stop fighting the defaults. Not a knock on Brandon's work, this feels alot like Ruby on Rails. The further I stray from the defaults, the harder I work. I'm using DayPlanner to be productive and I stopped being clever.

**Comment by brandonkboswell** [comment]
Sorry @mlevison and @kennonb, my plugin is using the periodic notes plugin to gather the documents, and it doesn't sound like Periodic Notes is identifying those notes. Maybe ask @liamcain how Periodic Notes fetches them.

**Comment by kennonb** [comment]
Thanks @brandonkboswell. No worries. I'll try it in a test vault later and see if I can figure it out.

@mlevison: I generally agree. I'm not trying to deviate too much, but just trying to have a little folder structure otherwise I get lost in the mountain of notes. The good, and bad, of Obsidian is the customization. I definitely can go down a rabbit hole if I'm not careful. I just liked the idea of this plugin since I really find a lot of value in seeing notes I've made across time. It's one of the reasons I should probably just use Day One only and be done with it. 😝

**Comment by mlevison** [comment]
Irony my Journalling came back to Obsidian because it DayOne is $$ and has failed to evolve in the past 18 months.

Most of what you want is possible, but you might have to write some code.
