### ISSUE TITLE
Documentation on how to use the plugin

### ISSUE THREAD

**Issue by egoexpress** [brandonkboswell/reflection#4]
Could you add some more documentation on how to configure and use this plugin in Obsidian?

Or should this work out of the box, e.g if I access a note named _2024-01-10_ and have a note _2023-01-10_ somewhere in my vault, it shows the latter to me? Where does it show up? Do I have to add some template code to the node _2024-01-10_ to display the note from former years?

**Comment by brandonkboswell** [comment]
Thank you for reaching out. I will add some additional documentation for this. This plugin builds on top of the Periodic Notes Plugin, which has a specific folder where your daily notes go. If you're using that plugin, and your notes are in the folder configured in the Periodic Notes Plugin, then the Reflection plugin should recognize the temporal relationship automatically for notes in those folders. Are you using the Periodic Notes plugin?

**Comment by egoexpress** [comment]
I'm using the Periodic Notes plugin. It is configured to use _2-Areas/Timestamps_ as _Note Folder_  and _YYYY/YYYY-MM/YYYY-MM-DD_ as format for the Daily Notes.

Using this setup I have two notes _2-Areas/Timestamps/2023/2023-01/2023-01-10_ and _2-Areas/Timestamps/2024/2024-01/2024-01-10_. If I understood if correctly, the 2023 one should somehow show up in _2024-01-10_, but I can't see anything.

**Comment by brandonkboswell** [comment]
Can you send me a screenshot of your Periodic Notes plugin settings? 

Here's mine to give you a feel for a configuration that does work with the Reflection Plugin: 
![BKB 2024-01-12 at 12 09 43](https://github.com/brandonkboswell/reflection/assets/921925/c3a7ad9c-1800-45d1-b781-06485ec22cba)

**Comment by egoexpress** [comment]
Sure, here's my setup.

![periodic-notes-setup](https://github.com/brandonkboswell/reflection/assets/2254804/c0bb9e09-d1f0-4230-8509-27330449512b)

**Comment by HerrC** [comment]
> Thank you for reaching out. I will add some additional documentation for this. This plugin builds on top of the Periodic Notes Plugin, which has a specific folder where your daily notes go. If you're using that plugin, and your notes are in the folder configured in the Periodic Notes Plugin, then the Reflection plugin should recognize the temporal relationship automatically for notes in those folders. Are you using the Periodic Notes plugin?

Do I have to use the Periodic Notes plugin or should it also work with the default Daily Notes plugin? Because at the moment no information is displayed in my Daily Notes.

Edit: I have kind of the same setup like egoexpress, just I use `YYYY/MM/YYYY-MM-DD`

**Comment by brandonkboswell** [comment]
You have to use the Periodic Notes plugin, but the good news is it's a
drop-in replacement (that is just better). Also the person who developed it
also developed the default Daily Notes Plugin.

**Comment by brandonkboswell** [comment]
Hey @egoexpress  @HerrC, I was able to test this and recreate the issue. There is a quirk in how I detect whether the current folder is your daily notes folder. I need to update this to be a bit smarter and still work when your periodic note structure generates a nested set of folders instead of a single folder. I will see if I can get a fix out shortly.

**Comment by brandonkboswell** [comment]
I just released version 1.0.2, and it should solve this issue.

**Comment by brandonkboswell** [comment]
Here's an example of it working and what to expect: 
![BKB 2024-01-28 at 14 02 55](https://github.com/brandonkboswell/reflection/assets/921925/6f7d63a9-d8f0-4c99-86dd-172947d7798a)

**Comment by egoexpress** [comment]
I can confirm that it works with my setup, it shows the entry from last year. Awesome, thanks for your work!

If I have an entry from two years ago, should this be shown as well? Or does the plugin 'only' show last years entry?

**Comment by brandonkboswell** [comment]
That's awesome to hear. It will show all previous entries in reverse
chronological order. For example, yesterday didn't have an entry from last
year, but it did from 2 years ago. If there had been one for each, then
both would have shown.
